### PR TITLE
set file mode when not using cache

### PR DESCRIPTION
**Pull request by pahoughton**

### CODE REVIEW

**Comment by braddeicide** [comment]
This works for me and solves #83 

I can't see what travis was sad about though, i get an error trying to view the logs

**Comment by spengilley** [comment]
Is this going to get merged?

**Comment by c33s** [comment]
@carlossg please merge this.
is this module still maintained? if not, what about handling it over to voxpupuli

see Migrating a module to voxpupuli @ https://voxpupuli.org/docs/

**Comment by carlossg** [comment]
I can move it to voxpupuli if somebody handles the move (PRs, issues,... ) I can do whatever only an admin is allowed to

**Comment by c33s** [comment]
@bastelfreak do you know how to move this module?

**Comment by bastelfreak** [comment]
Hi @carlossg, I added you to the correct Vox Pupuli group. You should now be able to migrate this module. Ping me if you want to migrate others as well.

**Comment by carlossg** [comment]
Thanks @bastelfreak I'm already an admin, I'm asking that @c33s or somebody willing to do the move goes through the process as much as possible, ie. all these steps

* Update the README.md with a description of the deprecation and a link to the new module location.
* Release a copy of your module to the ‘puppet’ forge account.
* Add the module to our modulesync setup.
* Add the module to our plumbing repository(handles travis secrets).
* Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with * * Write permissions (e.g. https://github.com/voxpupuli/puppet-gitlab/settings/collaboration).
* Execute modulesync for this module.
* Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well).

I can help where permissions are needed

**Comment by carlossg** [comment]
done

**Comment by Dan33l** [comment]
this module is now deprecated

**Pull request closed without merging**
