### PR TITLE
Support Puppet v4 AIO

### PR DESCRIPTION
**Pull request by ghoneycutt**
* Enables code to pass with strict variable checking.

* Supports and explicitly tests ruby 2.0.0, 2.1.0 and 2.3.1.

* Use puppet-lint v2.

* Use community puppet-lint plugins (style was already in compliance).

* Hiera bits were removed from spec tests because they were not actually
  being used and were getting in the way.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Hi @maestrodev 

I know this changes a few things you have in your modulesync, though I needed them to support the new AIO with ruby 2.3.1. I'm keen to get this merged for a client, let me know if there is anything you would like me to change.

**Comment by ju5t** [comment]
It would be good if this could be merged. @carlossg can you perhaps have a look at this?

**Comment by ghoneycutt** [comment]
I'm happy to rebase as needed, might need help on the modulesync stuff though.

**Comment by carlossg** [comment]
I'm not using this anymore, so if you want to take over happy to add to the repo

**Comment by ju5t** [comment]
@carlossg are there no maintainers left of this module? I'm sure people are happy to help out but it still needs to published to the Forge too.

**Comment by ghoneycutt** [comment]
@carlossg I'd be happy to and can communicate with the Forge maintainers. Could you please add me as an admin on here.

**Comment by carlossg** [comment]
@ghoneycutt you should be set with admin permissions. Tags are automatically deployed to the forge by Travis IIRC

**Comment by ghoneycutt** [comment]
Thanks @carlossg

**Comment by Dan33l** [comment]
this module is now deprecated

**Pull request closed without merging**
